[build]
  publish = "client/dist"
  command = "npm install --prefix client && npm run build --prefix client"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"

[context.production.environment]
  NODE_ENV = "production"
